#!/bin/sh
# autopkgtest check: Run the installed-tests to verify GTK works correctly
# Based on glib2.0's d/tests/installed-tests, (C) 2013 Canonical Ltd.

set -e

# Disable gvfs if it happens to be installed. We want to test the built-in
# stuff
export GIO_USE_VFS=local
export GIO_USE_VOLUME_MONITOR=unix

export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"

# We don't test under Wayland yet, because we don't have a Wayland
# equivalent of xvfb-run
export GDK_BACKEND=x11

tests=$(gnome-desktop-testing-runner -l gtk-4.0 |
    cut -f1 -d' ' |
    grep -v '^gtk-4.0/a11y/children.test$' |
    grep -v '^gtk-4.0/a11y/tests.test$' |
    grep -v '^gtk-4.0/a11y/tree.test$' |
    grep -v '^gtk-4.0/gtk/displayclose.test$' |
    grep -v '^gtk-4.0/gtk/icontheme.test$' |
    grep -v '^gtk-4.0/gtk/templates.test$')

exec dbus-run-session -- \
xvfb-run -a -s "-screen 0 1024x768x24" \
debian/run-with-locales \
    --generate de_DE.UTF-8 \
    --generate en_GB.UTF-8 \
    --generate en_US.UTF-8 \
    --generate sv_SE \
    -- \
gnome-desktop-testing-runner \
--report-directory="$AUTOPKGTEST_ARTIFACTS" \
--tap \
$tests
