#!/bin/sh -e
set -e

if [ "$1" = install ] || [ "$1" = upgrade ] ; then
    dpkg-divert --add --package libgtk-3-bin --rename \
        --divert /usr/sbin/update-icon-caches.gtk2 \
        /usr/sbin/update-icon-caches
    dpkg-divert --add --package libgtk-3-bin --rename \
        --divert /usr/share/man/man8/update-icon-caches.gtk2.8.gz \
        /usr/share/man/man8/update-icon-caches.8.gz
fi

#DEBHELPER#

exit 0
